---
- name: Deploy Kubernetes 
  hosts: all
  become: true
  tasks:
    - name: Copy Deployment File to Kubernetes Master
      copy: 
        src: deployment.yaml
        dest: /root/
    - name: Delete deployent (if any)
      command: kubectl delete --ignore-not-found=true -f /root/deployment.yaml
    - name: Create new deployment 
      command: kubectl apply -f /root/deployment.yaml
