apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpetclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springpetclinic
  template:
    metadata:
      labels:
        app: springpetclinic
    spec:
      containers:
        - name: app
          image: darrenchooji/spring-petclinic:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: springpetclinic-service
spec:
  type: NodePort
  selector:
    app: springpetclinic
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30001
